### ISSUE TITLE
crashes in WINE

### ISSUE THREAD

**Issue by kirjavascript** [dayvonjersen/chopsuey#1]
```
~/D/chopsuey-v0.7-BETA[tso]➤ wine chopsuey.exe
fixme:process:SetProcessPriorityBoost (0xffffffffffffffff,1): stub
fixme:virtual:create_view out of memory in virtual heap for 0xc000000000-0xc842002000
<SNIP(tso): 255 variations of above line>
fixme:systray:wine_notify_icon unhandled tray message: 4
2018/07/30 14:53:29 Shell_NotifyIcon

Stack:
goroutine 1 [running, locked to thread]:
runtime/debug.Stack(0xb62860, 0x431a53a8, 0x5197d3)
	C:/Go/src/runtime/debug/stack.go:24 +0xae
github.com/lxn/walk.newErr(0x8a83c3, 0x10, 0x0, 0x431a53d8)
	Z:/Users/Leek/Desktop/projects/go/gopath/src/github.com/lxn/walk/error.go:81 +0x2d
github.com/lxn/walk.newError(0x8a83c3, 0x10, 0x0, 0x1)
	Z:/Users/Leek/Desktop/projects/go/gopath/src/github.com/lxn/walk/error.go:85 +0x3c
github.com/lxn/walk.NewNotifyIcon(0x1008c, 0x431493b0, 0x431493b0, 0x0)
	Z:/Users/Leek/Desktop/projects/go/gopath/src/github.com/lxn/walk/notifyicon.go:109 +0x1d3
main.main()
	Z:/Users/Leek/Desktop/projects/go/gopath/src/github.com/generaltso/chopsuey/main.go:125 +0x54a
```

**Comment by generaltso** [comment]
welp.
